# .github/workflows/pr-tests.yaml
name: PR Tests

on:
  pull_request:
    branches:
      - release  # Только при PR в release-ветку

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      working-directory: ./lgbt
      run: pytest
