# .github/workflows/publish.yaml
name: Publish to PyPI

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
        
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build tools
      run: python -m pip install build twine

    - name: Build package
      working-directory: ./lgbt
      run: python -m build

    - name: Publish to PyPI
      working-directory: ./lgbt
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
